spring.application.name=reservation-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/reservationdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Kush@4148

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
